services:
  - type: web
    name: gamedailynews
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Gamedailynews.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Gamedailynews.settings
      - key: SECRET_KEY
        generateValue: true
